[[Qt6Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5de75dada379ee672dac16ae8577916cf40433ba"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "77125b7a99d5a18b8979728ff3971e5945886e640ba75e814a626e746ac4fa12"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+0/Qt6Base.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
